### ISSUE TITLE
housenumber/street

### ISSUE THREAD

**Issue by maxerickson** [atx-osg/atx-buildings#25]
I grabbed buildings-to-import.osm from https://github.com/wilsaj/atx-buildings/tree/with-import-data/osm/480219501003 and dumped the tags ( https://gist.github.com/maxerickson/ee1b419e69699e53c341 ).

One of the values for addr:street is "South Webberwood Way,1100", it would be good to check if that happens very often and try to handle it systematically if it does. I looked at the code for a minute but don't really see where to start looking where it might be dealt with.

**Comment by maxerickson** [comment]
Scanning the rest of the osm files, it seems to only happen with ",1100", there are about 200 occurrences.

**Comment by wilsaj** [comment]
Thanks for helping review!

That is indeed a bug with the way street name matching happens. We match to existing OSM street names in the area and there is some heuristics that go into determining a match. A score is tallied that gets calculated for possible matches, and the best one wins. This bug happens when a tie occurs where there are two positive matches with the same score (1100 in this case) - the shorter street name should win, but in this case the heuristic score is getting accidentally concatenated to the `addr:street` string. Oops.

The address processing happens in this script: https://github.com/atx-osg/atx-buildings/blob/master/scripts/convert-addresses.js#L201
