### ISSUE TITLE
Task #177 - addresses-to-import should be attached to buildings

### ISSUE THREAD

**Issue by jseppi** [atx-osg/atx-buildings#39]
Many of the addresses in this task look like they should be associated with buildings.

**Comment by jseppi** [comment]
![image](https://cloud.githubusercontent.com/assets/697848/11329184/1e4816a2-915e-11e5-84d8-d9f2af2a6b31.png)

**Comment by wilsaj** [comment]
Yeah, this is a weird one. Whether or not a building centroid lies in the block group is the test for inclusion in a blockgroup set. For these houses, the address points lie in this blockgroup and the buildings were allocated to the next one over. Usually block group boundaries follow street centerlines, but this one goes right through that row of houses for some reason. Probably don't need to worry about it since that is a really unusual case  `¯\_(ツ)_/¯`
